/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// HttpHeader struct for HttpHeader
type HttpHeader struct {
	// 请求头Key
	Key string `json:"key"`
	// 请求头Value
	Value string `json:"value"`
}
