/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TeamRegionsResp struct for TeamRegionsResp
type TeamRegionsResp struct {
	// region id
	RegionId string `json:"region_id"`
	// 数据中心名称
	RegionName string `json:"region_name"`
	// 数据中心别名
	RegionAlias string `json:"region_alias"`
	// 租户名称
	TenantName string `json:"tenant_name"`
	// 数据中心API url
	Url string `json:"url"`
	// 数据中心Websocket url
	Wsurl string `json:"wsurl"`
	// 数据中心http应用访问根域名
	Httpdomain string `json:"httpdomain"`
	// 数据中心tcp应用访问根域名
	Tcpdomain string `json:"tcpdomain"`
	// 数据中心token
	Token *string `json:"token,omitempty"`
	// 数据中心状态 0：编辑中 1:启用 2：停用 3:维护中
	Status string `json:"status"`
	// 数据中心描述
	Desc string `json:"desc"`
	// 数据中心范围 private|public
	Scope string `json:"scope,omitempty"`
}
