/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ServiceGroupOperations struct for ServiceGroupOperations
type ServiceGroupOperations struct {
	// 操作类型
	Action string `json:"action"`
	// 组件ID列表，不传值则操作应用下所有组件
	ServiceIds []string `json:"service_ids,omitempty"`
}
