/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdatePostHttpGatewayRule struct for UpdatePostHttpGatewayRule
type UpdatePostHttpGatewayRule struct {
	// 应用组件id
	ServiceId string `json:"service_id"`
	// 绑定端口
	ContainerPort int32 `json:"container_port,omitempty"`
	// 证书id
	CertificateId int32 `json:"certificate_id,omitempty"`
	// 域名
	DomainName string `json:"domain_name,omitempty"`
	// 域名cookie
	DomainCookie string `json:"domain_cookie,omitempty"`
	// 域名header
	DomainHeader string `json:"domain_header,omitempty"`
	TheWeight int32 `json:"the_weight,omitempty"`
	// 域名路径
	DomainPath string `json:"domain_path,omitempty"`
	// 规则扩展
	RuleExtensions []string `json:"rule_extensions,omitempty"`
	// 是否开放
	WhetherOpen bool `json:"whether_open,omitempty"`
	// 是否自动匹配证书，升级为https，如果开启，由外部服务完成升级
	AutoSsl bool `json:"auto_ssl,omitempty"`
	// 自动分发证书配置
	AutoSslConfig bool `json:"auto_ssl_config,omitempty"`
}
