/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ComponentMonitorSerializers struct for ComponentMonitorSerializers
type ComponentMonitorSerializers struct {
	Monitors *[]ComponentMonitorItemsSerializers `json:"monitors,omitempty"`
	// 组件昵称
	ServiceAlias string `json:"service_alias"`
	// 组件名
	ServiceCname string `json:"service_cname"`
	// 组件id
	ServiceId string `json:"service_id"`
}
