/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateTeamReq struct for CreateTeamReq
type CreateTeamReq struct {
	// 默认开通的数据中心，未指定则不开通
	Region string `json:"region,omitempty"`
	// 团队名称
	TenantName string `json:"tenant_name"`
}
