/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// HttpConfiguration 高级参数配置
type HttpConfiguration struct {
	// 请求主体大小
	ProxyBodySize int32 `json:"proxy_body_size,omitempty"`
	// 缓冲区数量
	ProxyBufferNumbers int32 `json:"proxy_buffer_numbers,omitempty"`
	// 缓冲区大小
	ProxyBufferSize int32 `json:"proxy_buffer_size,omitempty"`
	// 是否开启ProxyBuffer
	ProxyBuffering string `json:"proxy_buffering,omitempty"`
	// 连接超时时间
	ProxyConnectTimeout int32 `json:"proxy_connect_timeout,omitempty"`
	// 读超时时间
	ProxyReadTimeout int32 `json:"proxy_read_timeout,omitempty"`
	// 发送超时时间
	ProxySendTimeout int32 `json:"proxy_send_timeout,omitempty"`
	SetHeaders []HttpHeader `json:"set_headers"`
}
