/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Upgrade struct for Upgrade
type Upgrade struct {
	UpdateVersions []UpgradeBase `json:"update_versions"`
}
