/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TeamOverview struct for TeamOverview
type TeamOverview struct {
	// 应用总数
	AppNums int32 `json:"app_nums,omitempty"`
	// 组件总数
	ComponentNums int32 `json:"component_nums,omitempty"`
	// cpu总额
	TotalCpu int32 `json:"total_cpu,omitempty"`
	// 内存总额
	TotalMemory int32 `json:"total_memory,omitempty"`
	// 占用cpu
	UsedCpu int32 `json:"used_cpu,omitempty"`
	// 占用内存
	UsedMemory int32 `json:"used_memory,omitempty"`
}
