/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListUsersRespView struct for ListUsersRespView
type ListUsersRespView struct {
	Users []UserInfo `json:"users"`
	Total int32 `json:"total"`
}
