/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PostTcpGatewayRuleExtensions 规则扩展
type PostTcpGatewayRuleExtensions struct {
	Key string `json:"key"`
	Value string `json:"value"`
}
