/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OauthServicesBaseResp struct for OauthServicesBaseResp
type OauthServicesBaseResp struct {
	Enable bool `json:"enable,omitempty"`
	Value []OauthServicesResp `json:"value,omitempty"`
}
