/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AppBaseInfo struct for AppBaseInfo
type AppBaseInfo struct {
	ID int32 `json:"ID,omitempty"`
	// 租户id
	TenantId string `json:"tenant_id"`
	// 组名
	GroupName string `json:"group_name"`
	// 区域中心名称
	RegionName string `json:"region_name"`
	// 默认组件
	IsDefault bool `json:"is_default,omitempty"`
	// 应用排序
	OrderIndex int32 `json:"order_index,omitempty"`
	// 备注
	Note *string `json:"note,omitempty"`
}
