/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ExportAppBaseResp struct for ExportAppBaseResp
type ExportAppBaseResp struct {
	Enable bool `json:"enable,omitempty"`
	Value *string `json:"value,omitempty"`
}
