/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AppCopyModify struct for AppCopyModify
type AppCopyModify struct {
	Change string `json:"change,omitempty"`
	// id
	ServiceId string `json:"service_id"`
}
