/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TenantRegionList struct for TenantRegionList
type TenantRegionList struct {
	// 数据中心名称
	RegionName string `json:"region_name"`
	// 租户id
	TenantId string `json:"tenant_id"`
}
