/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AppInfo struct for AppInfo
type AppInfo struct {
	ID int32 `json:"ID,omitempty"`
	// 企业ID(联合云ID)
	EnterpriseId string `json:"enterprise_id"`
	// 组件数量
	ServiceCount int32 `json:"service_count"`
	// 正在运行的组件数量
	RunningServiceCount int32 `json:"running_service_count"`
	// 分配的内存
	UsedMomory int32 `json:"used_momory"`
	// 分配的cpu
	UsedCpu int32 `json:"used_cpu"`
	// 应用id
	AppId int32 `json:"app_id"`
	// 团队名
	TeamName string `json:"team_name"`
	// 应用状态
	Status string `json:"status"`
	// 租户id
	TenantId string `json:"tenant_id"`
	// 组名
	GroupName string `json:"group_name"`
	// 区域中心名称
	RegionName string `json:"region_name"`
	// 默认组件
	IsDefault bool `json:"is_default,omitempty"`
	// 应用排序
	OrderIndex int32 `json:"order_index,omitempty"`
	// 备注
	Note *string `json:"note,omitempty"`
}
