/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AppServiceTelescopicHorizontal struct for AppServiceTelescopicHorizontal
type AppServiceTelescopicHorizontal struct {
	// 组件节点
	NewNode int32 `json:"new_node"`
}
