/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateAdminUserReq struct for CreateAdminUserReq
type CreateAdminUserReq struct {
	// 企业ID
	Eid string `json:"eid"`
	// 用户ID
	UserId string `json:"user_id"`
}
