/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpgradeBase struct for UpgradeBase
type UpgradeBase struct {
	// 应用模型id
	AppModelId string `json:"app_model_id"`
	// 当前版本
	AppModelVersion string `json:"app_model_version"`
	// 应用商店名称
	MarketName string `json:"market_name"`
}
