/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListTeamRegionsResp struct for ListTeamRegionsResp
type ListTeamRegionsResp struct {
	Regions []TeamRegionsResp `json:"regions"`
	Total int32 `json:"total"`
}
