/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AddRegionRequest struct for AddRegionRequest
type AddRegionRequest struct {
	CertFile string `json:"cert_file,omitempty"`
	Desc string `json:"desc,omitempty"`
	Httpdomain string `json:"httpdomain"`
	KeyFile string `json:"key_file,omitempty"`
	RegionAlias string `json:"region_alias"`
	RegionName string `json:"region_name"`
	Scope string `json:"scope,omitempty"`
	SslCaCert string `json:"ssl_ca_cert,omitempty"`
	Status int32 `json:"status,omitempty"`
	Tcpdomain string `json:"tcpdomain"`
	Url string `json:"url"`
	Wsurl string `json:"wsurl"`
}
