/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AppStoreImageHubResp struct for AppStoreImageHubResp
type AppStoreImageHubResp struct {
	Namespace *string `json:"namespace,omitempty"`
	HubPassword *string `json:"hub_password,omitempty"`
	HubUrl *string `json:"hub_url,omitempty"`
	HubUser *string `json:"hub_user,omitempty"`
}
