/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ComponentEnvsSerializers struct for ComponentEnvsSerializers
type ComponentEnvsSerializers struct {
	Envs []ComponentEnvsBaseSerializers `json:"envs"`
}
