/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Install struct for Install
type Install struct {
	// 应用id
	AppModelId string `json:"app_model_id"`
	// 应用版本
	AppModelVersion string `json:"app_model_version"`
	// 应用商店令牌
	MarketAccessKey string `json:"market_access_key"`
	// 应用商店domain
	MarketDomain string `json:"market_domain"`
	// 应用商店类型
	MarketType string `json:"market_type"`
	// 应用商店路由
	MarketUrl string `json:"market_url"`
}
