/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OauthServicesResp struct for OauthServicesResp
type OauthServicesResp struct {
	AccessTokenUrl string `json:"access_token_url,omitempty"`
	ApiUrl string `json:"api_url,omitempty"`
	AuthUrl string `json:"auth_url,omitempty"`
	Eid string `json:"eid"`
	Enable bool `json:"enable,omitempty"`
	HomeUrl *string `json:"home_url,omitempty"`
	IsAutoLogin bool `json:"is_auto_login,omitempty"`
	IsConsole bool `json:"is_console,omitempty"`
	IsDeleted bool `json:"is_deleted,omitempty"`
	IsGit bool `json:"is_git,omitempty"`
	Name string `json:"name"`
	OauthType string `json:"oauth_type"`
	ServiceId *int32 `json:"service_id,omitempty"`
}
