/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// AppInfo struct for AppInfo
type AppInfo struct {
	ID int32 `json:"ID,omitempty"`
	// 应用id
	AppId int32 `json:"app_id"`
	// 创建时间
	CreateTime time.Time `json:"create_time"`
	// 企业ID(联合云ID)
	EnterpriseId string `json:"enterprise_id"`
	// governance mode
	GovernanceMode *string `json:"governance_mode,omitempty"`
	// 组名
	GroupName string `json:"group_name"`
	// 默认组件
	IsDefault bool `json:"is_default,omitempty"`
	// 备注
	Note *string `json:"note,omitempty"`
	// 应用排序
	OrderIndex int32 `json:"order_index,omitempty"`
	// 区域中心名称
	RegionName string `json:"region_name"`
	// 正在运行的组件数量
	RunningServiceCount int32 `json:"running_service_count"`
	// 组件数量
	ServiceCount int32 `json:"service_count"`
	// 应用状态
	Status string `json:"status"`
	// 团队名
	TeamName string `json:"team_name"`
	// 租户id
	TenantId string `json:"tenant_id"`
	// 更新时间
	UpdateTime time.Time `json:"update_time"`
	// 分配的cpu
	UsedCpu int32 `json:"used_cpu"`
	// 分配的内存
	UsedMomory int32 `json:"used_momory"`
	// the username of principal
	Username *string `json:"username,omitempty"`
}
