/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TeamRegionReq struct for TeamRegionReq
type TeamRegionReq struct {
	// 数据中心名称
	Region string `json:"region,omitempty"`
}
