/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ComponentEnvsBaseSerializers struct for ComponentEnvsBaseSerializers
type ComponentEnvsBaseSerializers struct {
	// 备注
	Note string `json:"note,omitempty"`
	// 环境变量名
	Name string `json:"name"`
	// 环境变量值
	Value string `json:"value"`
	// 是否可改变
	IsChange bool `json:"is_change,omitempty"`
	// 范围
	Scope string `json:"scope,omitempty"`
}
