/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TeamAppsCloseSerializers struct for TeamAppsCloseSerializers
type TeamAppsCloseSerializers struct {
	ServiceIds []string `json:"service_ids,omitempty"`
}
