/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListTeamResp struct for ListTeamResp
type ListTeamResp struct {
	Total int32 `json:"total,omitempty"`
	Tenants []TeamInfo `json:"tenants"`
}
