/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GatewayRule struct for GatewayRule
type GatewayRule struct {
	Http []HttpGatewayRule `json:"http,omitempty"`
	Tcp []TcpGatewayRule `json:"tcp,omitempty"`
}
