/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CustomJwt struct for CustomJwt
type CustomJwt struct {
	NickName string `json:"nick_name"`
	Password string `json:"password"`
}
