/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateThirdComponent struct for CreateThirdComponent
type CreateThirdComponent struct {
	// 组件名称
	ComponentName string `json:"component_name"`
	// Endpoint 列表
	Endpoints []string `json:"endpoints"`
	// Endpoint 注册方式
	EndpointsType string `json:"endpoints_type"`
}
