/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// ServiceBaseInfo struct for ServiceBaseInfo
type ServiceBaseInfo struct {
	// 组件状态
	Status string `json:"status,omitempty"`
	// 组件id
	ServiceId string `json:"service_id"`
	// 租户id
	TenantId string `json:"tenant_id"`
	// 组件key
	ServiceKey string `json:"service_key"`
	// 组件别名
	ServiceAlias string `json:"service_alias"`
	// 组件名
	ServiceCname string `json:"service_cname,omitempty"`
	// 组件所属区
	ServiceRegion string `json:"service_region"`
	// 描述
	Desc *string `json:"desc,omitempty"`
	// 组件分类：application,cache,store
	Category string `json:"category"`
	// 版本
	Version string `json:"version"`
	// 内部发布次数
	UpdateVersion int32 `json:"update_version,omitempty"`
	// 镜像
	Image string `json:"image"`
	// 启动参数
	Cmd *string `json:"cmd,omitempty"`
	// 组件部署类型,stateless or state
	ExtendMethod string `json:"extend_method,omitempty"`
	// 启动个数
	MinNode int32 `json:"min_node,omitempty"`
	// cpu个数
	MinCpu int32 `json:"min_cpu,omitempty"`
	// 内存大小单位（M）
	MinMemory int32 `json:"min_memory,omitempty"`
	// 代码来源:gitlab,github
	CodeFrom *string `json:"code_from,omitempty"`
	// code代码仓库
	GitUrl *string `json:"git_url,omitempty"`
	// 创建时间
	CreateTime time.Time `json:"create_time,omitempty"`
	// gitlab 中项目id
	GitProjectId int32 `json:"git_project_id,omitempty"`
	// 代码版本
	CodeVersion *string `json:"code_version,omitempty"`
	// 组件类型:web,mysql,redis,mongodb,phpadmin
	ServiceType *string `json:"service_type,omitempty"`
	// 组件创建者
	Creater int32 `json:"creater,omitempty"`
	// 代码语言
	Language *string `json:"language,omitempty"`
	// 内存使用M
	TotalMemory int32 `json:"total_memory,omitempty"`
	// 是否inner组件
	IsService bool `json:"is_service,omitempty"`
	// 组件创建类型cloud云市组件,assistant云帮组件
	ServiceOrigin string `json:"service_origin,omitempty"`
	// 过期时间
	ExpiredTime *time.Time `json:"expired_time,omitempty"`
	// 组件归属的组件组id
	TenantServiceGroupId int32 `json:"tenant_service_group_id,omitempty"`
	// 是否开启自动触发部署功能（兼容老版本组件）
	OpenWebhooks bool `json:"open_webhooks,omitempty"`
	// 组件来源(source_code, market, docker_run, docker_compose)
	ServiceSource *string `json:"service_source,omitempty"`
	// 组件创建状态 creating|complete
	CreateStatus *string `json:"create_status,omitempty"`
	// 更新时间
	UpdateTime time.Time `json:"update_time,omitempty"`
	// 组件检测ID
	CheckUuid *string `json:"check_uuid,omitempty"`
	// 组件检测事件ID
	CheckEventId *string `json:"check_event_id,omitempty"`
	// 镜像创建命令
	DockerCmd *string `json:"docker_cmd,omitempty"`
	// 源码仓库类型
	ServerType string `json:"server_type,omitempty"`
	// 是否可以更新
	IsUpgrate bool `json:"is_upgrate,omitempty"`
	// 组件构建后是否升级
	BuildUpgrade bool `json:"build_upgrade,omitempty"`
	// 拉取源码所用的OAuth服务id
	OauthServiceId *int32 `json:"oauth_service_id,omitempty"`
}
