/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PostGatewayRule struct for PostGatewayRule
type PostGatewayRule struct {
	// 协议
	Protocol string `json:"protocol"`
	Tcp PostTcpGatewayRule `json:"tcp,omitempty"`
	Http PostHttpGatewayRule `json:"http,omitempty"`
}
