/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AppStoreImageHubBaseResp struct for AppStoreImageHubBaseResp
type AppStoreImageHubBaseResp struct {
	Enable bool `json:"enable,omitempty"`
	Value AppStoreImageHubResp `json:"value,omitempty"`
}
