/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AppServiceTelescopicVertical struct for AppServiceTelescopicVertical
type AppServiceTelescopicVertical struct {
	// 组件内存
	NewMemory int32 `json:"new_memory"`
}
