/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ObjectStorageBaseResp struct for ObjectStorageBaseResp
type ObjectStorageBaseResp struct {
	Enable bool `json:"enable,omitempty"`
	Value ObjectStorageResp `json:"value,omitempty"`
}
