/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ChangePassWdUser struct for ChangePassWdUser
type ChangePassWdUser struct {
	// user_id
	UserId int32 `json:"user_id"`
	// 新密码
	Password string `json:"password"`
	// 再次确认新密码
	Password1 string `json:"password1"`
}
