/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PostHttpGatewayRule struct for PostHttpGatewayRule
type PostHttpGatewayRule struct {
	// 是否自动匹配证书，升级为https，如果开启，由外部服务完成升级
	AutoSsl bool `json:"auto_ssl,omitempty"`
	// 自动分发证书配置
	AutoSslConfig string `json:"auto_ssl_config,omitempty"`
	// 证书id
	CertificateId int32 `json:"certificate_id,omitempty"`
	Configuration HttpConfiguration `json:"configuration,omitempty"`
	// 绑定端口
	ContainerPort int32 `json:"container_port"`
	// 域名cookie
	DomainCookie string `json:"domain_cookie,omitempty"`
	// 域名header
	DomainHeader string `json:"domain_header,omitempty"`
	// 域名
	DomainName string `json:"domain_name"`
	// 域名路径
	DomainPath string `json:"domain_path,omitempty"`
	// 规则扩展
	RuleExtensions []string `json:"rule_extensions,omitempty"`
	// 应用组件id
	ServiceId string `json:"service_id"`
	TheWeight int32 `json:"the_weight,omitempty"`
	// 是否开放
	WhetherOpen bool `json:"whether_open,omitempty"`
}
